version: "3.9"

services:

  nginx:
    image: nginx:1.7
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ".:/var/www/html"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ".:/var/www/html"
      - "./php.ini:/usr/local/etc/php/conf.d/php.ini"
    links:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_ROOT_PASSWORD: '123456'

volumes:
  mysql:

